# Generated by Django 4.2 on 2023-05-25 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            (
                                "Sport",
                                (
                                    ("running", "Running"),
                                    ("jumping", "Jumping"),
                                    ("cycling", "Cycling"),
                                ),
                            ),
                            (
                                "Programming",
                                (
                                    ("python", "Python"),
                                    ("javascript", "JavaScript"),
                                    ("java", "Java"),
                                    ("react", "React"),
                                ),
                            ),
                            (
                                "Else",
                                (
                                    ("cooking", "Cooking"),
                                    ("building", "Building"),
                                    ("driving", "Driving"),
                                    ("traveling", "Traveling"),
                                ),
                            ),
                        ],
                        default="none",
                        max_length=100,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
