# Generated by Django 4.2 on 2023-05-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0004_alter_post_public_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_comment", "0002_alter_comment_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core_post.post"
            ),
        ),
    ]
