# Generated by Django 4.2 on 2023-04-14 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0002_alter_post_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("498ab434-4877-4e9a-b916-96c07364b694"),
                editable=False,
                unique=True,
            ),
        ),
    ]
