# Generated by Django 4.2 on 2023-04-26 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0003_alter_post_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
