# Generated by Django 4.2 on 2023-06-05 06:42

import core.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0004_alter_post_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="contacts",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="event_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.post.models.post_directory_path
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
    ]
