# Generated by Django 4.2 on 2023-04-12 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_user_bio_alter_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user/avatar/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("56d05f79-ff06-45db-96d3-939dd44a8059"),
                editable=False,
                unique=True,
            ),
        ),
    ]
