# Generated by Django 4.2 on 2023-04-13 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_user_avatar_alter_user_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("9d4b6777-43eb-4d4c-93d9-b7b5136cd97c"),
                editable=False,
                unique=True,
            ),
        ),
    ]
