# Generated by Django 4.2 on 2023-04-26 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_comment", "0002_alter_comment_public_id"),
        ("core_user", "0006_alter_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments_liked",
            field=models.ManyToManyField(
                related_name="commented_by", to="core_comment.comment"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
