# Generated by Django 4.2 on 2023-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0008_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(blank=True, to="core_user.interest"),
        ),
    ]
