# Generated by Django 4.2 on 2023-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0009_interest_user_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(to="core_user.interest"),
        ),
    ]
