name: Build, Test and Deploy Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Injecting env vars
        run: |
          echo "SECRET_KEY=e2=@q+4vht!%427z&%5s5psg$^_*dr0v(k%q=m_k$$tg@vug
                DATABASE_NAME=coredb
                DATABASE_USER=core
                DATABASE_PASSWORD=12345q
                DATABASE_HOST=postagram_db
                DATABASE_PORT=5432
                POSTGRES_USER=core
                POSTGRES_PASSWORD=12345q
                POSTGRES_DB=coredb
                ENV=DEV
                DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
                " >> .env

      - name: Building containers
        run: docker-compose up -d --build

      - name: Running Tests
        run: docker-compose exec -T api pytest
