name: Build, Test and Deploy Postagram backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Injecting env vars
        run: |
          echo "${{ secrets.TEST_SECRETS }}" >> .env

      - name: Building containers
        run: |
          docker-compose up -d --build
          docker-compose logs

      - name: Running Tests inside Docker containers
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/web_dev
          DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/web_test
        run: docker-compose exec -T api pytest

  deploy:
    name: Deploying on EC2 via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Applications on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_EC2_IP }}
          username: ${{ secrets.SSH_EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/.scripts
            ./docker-ec2-deploy.sh
      - name: Debug
        if: ${{ failure() }}
        run: |
          echo "Failed. Debugging info:"
          echo "=================================="
          sudo grep sshd /var/log/auth.log | grep '2023-05-07 21:20:00' -A 50
          echo "=================================="
